# Application related configurations
mutationRate: 0.01
crossoverRate: 0.9
initialPopulationSize: 100
elitismCount: 2
tournamentCount: 5
maxGenerations: 1000

# Weights as a percentage '%'
weightFollowOnClasses: 5