Classrooms:
  - number: A1
    capacity: 15
  - number: B1
    capacity: 30
  - number: D1
    capacity: 20
  - number: F1
    capacity: 25

Professors:
  - "Dr. P Smith"
  - "Mrs. E Mitchell"
  - "Dr. R Williams"
  - "Mr. A Thompson"

Modules:
  - name: "Computer Science"
    professors: [1, 3]
  - name: "English"
    professors: [2, 3]
  - name: "Maths"
    professors: [1, 2]
  - name: "Physics"
    professors: [3, 4]
  - name: "History"
    professors: [4]
  - name: "Drama"
    professors: [1, 4]